deployment:
  resources:
    requests:
      cpu: 1000m
      memory: 1250Mi
    limits:
      cpu: 3000m
      memory: 3000Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
      scheme: HTTP
  readinessProbe:
    httpGet:
      path: /
      port: 80
      scheme: HTTP
dns:
  dnsName: bv-slate-docs.bv-sandbox.validity.com
  target: stock-web-public-546137840.us-east-1.elb.amazonaws.com
ingress:
  albName: "stock-web-public"
  healthCheckPath: "/"
  ingressClass: "rpalb"
  servicePort: 80
